---
- name: Converge
  hosts: all
  roles:
    - role: genlab.docker_ubuntu

    - role: genlab.nginx_docker
      site_config: "nginx/test.conf"
      custom_volumes:
        - {from: /mnt, to: /mnt, mode: ro}
