---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: "Make an HTTP query"
      register: this
      failed_when: this is failed or 'healthy' not in this.content
      ansible.builtin.uri:
        url: "http://localhost:80/health/startup"
        method: "GET"
        return_content: true
