---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: "Make an HTTP query"
      register: this
      vars:
        expected: "<h1>Welcome to nginx!</h1>"
      failed_when: this is failed or expected not in this.content
      ansible.builtin.uri:
        url: "http://localhost:80"
        method: "GET"
        return_content: true
